# Generated by Django 4.0.3 on 2022-05-24 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_genre_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
