# Generated by Django 4.0.3 on 2022-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_backdrop_path_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
