# Generated by Django 4.0.4 on 2022-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('genre_id', models.CharField(blank=True, max_length=10, null=True)),
                ('movie', models.ManyToManyField(to='core.movie')),
            ],
        ),
    ]
