# Generated by Django 4.0.3 on 2022-05-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
