# Generated by Django 4.0.3 on 2022-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_genres_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(related_name='movies', to='core.movie'),
        ),
    ]
